name: deathCoordinate
version: '${version}'
main: vg.h2o.deathcoordinate.DeathCoordinate
api-version: 1.19

commands:
  removeItemDespawnTimer:
    description: Removes itemDespawnTimer
    aliases:
      - ridt